### PR TITLE
fix: only count products towards discount that are not optional or optional and selected

### LINKED ISSUE #22: Items with a quantity that are not selected count towards the bundle discount
**Observed behavior**

If you use the `WC_PB()->cart->add_bundle_to_cart()` function and pass a configuration array that contains items similar to this:

```php
[
    /* ...more item data... */
    'quantity' => 1,
    'optional_selected' => false,
]
```

Assuming that this item is optional, the bundled item in the cart will still count towards the bulk discount even though it is not actually added to the cart (because its optional and not selected). This means that the customer would get a discount he or she is not qualified for.

**Expected behavior**

The expected behavior might be one of the two:
1. Only count quantity if optional_selected is true (my preferred variant)
2. Throw an error when validating a configuration array that contains an item that is not selected, but has a quantity > 0. This, however, would probably require modifications to the documentation as well and makes development more difficult.

**Potential sources of error**

I found the following code:
https://github.com/somewherewarm/woocommerce-product-bundles-bulk-discounts/blob/43b491f27b857a489c9c2af636a9d3b49f8dd1f0/product-bundles-bulk-discounts-for-woocommerce.php#L476

Here, it should probably also be checked whether optional_selected is true instead of blindly adding all stamps to the cart.

### PR DESCRIPTION
**Pull request by leonclaus**
Should resolve #22.

Only counts products into the total_quantity if they are
a. Not optional OR
b. have `optional_selected === 'yes'` set.

This solution seems to work for our cases, but please validate on your own.

### CODE REVIEW

File: product-bundles-bulk-discounts-for-woocommerce.php [hunk 1]
```diff
@@ -471,9 +471,12 @@ public static function bundled_cart_item_discount( $cart_item, $bundle ) {
...
 				$bundled_items_data = $container[ 'stamp' ];
 				$total_quantity     = 0;
+				$bundled_items      = $container[ 'data' ]->get_bundled_items();
 
-				foreach ( $bundled_items_data as $bundled_item_data ) {
-					if ( isset( $bundled_item_data[ 'quantity' ] ) ) {
+				foreach ( $bundled_items_data as $bundled_item_id => $bundled_item_data ) {
+					$bundled_item = $bundled_items[ $bundled_item_id ];
+
+					if ( isset( $bundled_item_data[ 'quantity' ] ) && ( ! $bundled_item->is_optional() || ( isset( $bundled_item_data[ 'optional_selected' ] ) && $bundled_item_data[ 'optional_selected' ] === 'yes' ) ) ) {
```
Comment (manospsyx) [inline product-bundles-bulk-discounts-for-woocommerce.php]: It probably won't make much of a difference performance-wise, but how about changing this line to:

`if ( isset( $bundled_item_data[ 'quantity' ] ) && ( ! isset( $bundled_item_data[ 'optional_selected' ] ) || $bundled_item_data[ 'optional_selected' ] === 'yes' ) ) {`

Then L474 won't be needed. 

Again, bundled item objects are runtime-cached, so `get_bundled_items` doesn't really add any overhead -- but if everything we need is in the `$bundled_item_data` array, it wouldn't hurt to skip that `get_bundled_items` call.

File: product-bundles-bulk-discounts-for-woocommerce.php [hunk 2]
```diff
@@ -516,9 +519,12 @@ public static function bundle_container_cart_item_discount( $cart_item, $bundle
...
 				$bundled_items_data = $cart_item[ 'stamp' ];
 				$total_quantity     = 0;
+				$bundled_items      = $cart_item[ 'data' ]->get_bundled_items();
+
+				foreach ( $bundled_items_data as $bundled_item_id => $bundled_item_data ) {
+					$bundled_item = $bundled_items[ $bundled_item_id ];
 
-				foreach ( $bundled_items_data as $bundled_item_data ) {
-					if ( isset( $bundled_item_data[ 'quantity' ] ) ) {
+					if ( isset( $bundled_item_data[ 'quantity' ] ) && ( ! $bundled_item->is_optional() || ( isset( $bundled_item_data[ 'optional_selected' ] ) && $bundled_item_data[ 'optional_selected' ] === 'yes' ) ) ) {
```
Comment (manospsyx) [inline product-bundles-bulk-discounts-for-woocommerce.php]: Same as above?

**Review by manospsyx — COMMENTED** [review]
Thanks so much for submitting a PR @leonclaus 🥇 

Left some feedback for you here.

File: product-bundles-bulk-discounts-for-woocommerce.php (hunk 1 above)
Comment (leonclaus) [reply product-bundles-bulk-discounts-for-woocommerce.php]: I am not entirely sure about how the main plugin handles this, but this might lead to issues in cases where the product is optional but the `$bundle_configuration` array does not contain a `optional_selected` key. The product would then be added to the discount quantity. Now whether this is correct is obviously up to you guys, but I would have thought that `optional_selected` would default to `no` (and thus the product not being added) when an item is optional.

Comment (manospsyx) [reply product-bundles-bulk-discounts-for-woocommerce.php]: > in cases where the product is optional but the `$bundle_configuration` array does not contain a `optional_selected` key.

Hmmm... this should never happen with posted data. If a bundled item is optional and the config array is manually supplied (for example via custom code), then it's up to the developer to supply correct data.

The integrity of the config array is always validated on the `woocommerce_check_cart_items` hook -- so if a config is "stale" you'll get an error in the cart, and will not be able to proceed to checkout.

**Comment by leonclaus** [comment]
@franticpsyx Implemented your feedback. Please have a look :)

**Comment by manospsyx** [comment]
Looks great, thanks so much @leonclaus

**Comment by jimjasson** [comment]
@franticpsyx I tested this PR locally and I confirmed that it resolves the reported issue. Thanks again @leonclaus! 🤗
